version: "3.9"

services:
  grass:
    container_name: grass-community-store-grass
    hostname: umbrel-grass-node
    image: nottherealjoe/grass-desktop:latest
    environment:
      - VNC_PASSWORD=cambiapassword
      - GRASS_USERNAME=oliveripietro996@gmail.com
      - GRASS_PASS=Grass2024!
    ports:
      - "5900:5900/tcp"
    restart: unless-stopped
