version: "3.9"

services:
  grass:
    container_name: grass-community-store-grass
    hostname: umbrel-grass-node
    image: mrcolorrain/grass:latest
    environment:
      - GRASS_USER=oliveripietro996@gmail.com
      - GRASS_PASS=Grass2024!
    restart: unless-stopped
