version: "3.9"
services:
  grass-desktop:
    container_name: grass-desktop
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    security_opt:
      - seccomp:unconfined # Necessario per far girare il browser dentro il container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - SUBFOLDER=/ # Fondamentale per Umbrel
    ports:
      - "6080:3000" # Mappa la porta 3000 interna alla 6080 esterna per il tuo browser
    shm_size: "1gb" # Evita che il browser crashi
    restart: unless-stopped
